<?php

/**
 * @file
 * The 403 to page module functions.
 */

/**
 * Implements hook_menu().
 */
function m4032page_menu() {
  $items = array();
  $items['m4032page'] = array(
    'title'           => '403 to page callback',
    'page callback'   => 'm4032page_callback',
    // Everyone can access the url.
    'access callback' => TRUE,
    'type'            => MENU_CALLBACK,
  );
  $items['admin/config/system/m4032page'] = array(
    'type'              => MENU_NORMAL_ITEM,
    'title'             => '403 to page Settings',
    'description'       => 'Settings for 403 to page depend on user role',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('m4032page_admin_settings'),
    'access arguments'  => array('administer site configuration'),
  );
  return $items;
}

/**
 * Page callback for m4032page.
 */
function m4032page_callback() {
  global $user;
  $roles = array_keys($user->roles);
  rsort($roles);
  $rid = reset($roles);
  $path = variable_get('m4032page_role_' . $rid, '<front>');

  header('Location: ' . $path, TRUE, 302);
  drupal_exit();
}

/**
 * Settings form for redirection destination depend on roles.
 */
function m4032page_admin_settings() {
  $form = array();
  $roles = user_roles();

  $form['redirect_role'] = array(
    '#type'        => 'fieldset',
    '#title'       => t('Redirect destination per role'),
    '#collapsible' => TRUE,
    '#collapsed'   => FALSE,
  );

  foreach (array_keys($roles) as $rid) {
    $form['redirect_role']['m4032page_role_' . $rid] = array(
      '#title'         => t('":role" users redirect path', array(':role' => $roles[$rid])),
      '#type'          => 'textfield',
      '#default_value' => variable_get('m4032page_role_' . $rid, ''),
    );
  }

  return system_settings_form($form);
}
